name: e2e

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.6'
      - name: Pull browsers
        run: |     
          docker pull selenoid/vnc_chrome:127.0
      - name: Run tests
        env:
          ARCH: amd64
          ALLURE_DOCKER_API: ${{ secrets.ALLURE_DOCKER_API }}
          BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          HEAD_COMMIT_MESSAGE: ${{ github.event.pull_request.head.sha || github.sha }}
          EXECUTION_TYPE: github
        run: |
          : # build backends with profile `docker`, only for testing
          bash ./gradlew jibDockerBuild -x :rangiffler-e2e:test || exit 1
          : # run e2e tests
          docker compose -f docker-compose-test.yml up -d
          docker ps -a
          docker wait rangiffler-e2e
          exit_code=$(docker inspect -f '{{.State.ExitCode}}' rangiffler-e2e)
          echo "e2e_exit_code=$exit_code" >> $GITHUB_OUTPUT
          echo "### Test logs ###"
          docker logs rangiffler-e2e
          docker compose -f docker-compose-test.yml down
          docker system prune -a -f
          if [ "$exit_code" -eq "0" ]; then
            echo "Tests passed successfully!"
            exit 0
          else
            echo "Tests failed!"
            exit 1
          fi
      - name: Add comment to PR with link to allure
        if: always()
        uses: actions/github-script@v6
        with:
          script: |
            const issues = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            })
            const pr = context.issue.number || issues.data[0].number
            const exitCode = ${{ steps.e2e.outputs.e2e_exit_code }}
            const message = exitCode == '0' ? 
              '✅ TEST RUN PASSED ✅ There is the [report](https://allure.niffler-stage.qa.guru/api/allure-docker-service/projects/rangiffler/reports/latest/index.html)\n🕓 All reports [history](https://allure.niffler-stage.qa.guru/allure-docker-service-ui/projects/rangiffler)' :
              '🔴 TEST RUN FAILED 🔴 There is the [report](https://allure.niffler-stage.qa.guru/api/allure-docker-service/projects/rangiffler/reports/latest/index.html)\n🕓 All reports [history](https://allure.niffler-stage.qa.guru/allure-docker-service-ui/projects/rangiffler)'
            github.rest.issues.createComment({
              issue_number: pr,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            })
